---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
        id: test

      - name: Check Test Result
        if: steps.test.outcome == 'failure'
        run: echo "Test failed, stopping workflow" && exit 1

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
